"""Build a single-file Windows .exe with PyInstaller.

Run:
    pip install pyinstaller
    python build_exe.py               # standard build, no debug logging
    python build_exe.py --debug-logging  # enables gui.log in the built exe

Produces `dist/MPCFillToPDF.exe`. The .exe is portable: drop it in any
folder and it will create `MPCFillToPDF/archivos generados/` and
`MPCFillToPDF/procesamiento/` next to itself.

API key embedding
-----------------
If `config.json` contains a valid `google_drive_api_key`, it is XOR-encoded
with a random mask and baked into `src/_bundled_key.py` before packaging.
PyInstaller bundles that module; at runtime the app decodes and uses the key
in memory.  The key never appears as a plain string inside the binary.

`src/_bundled_key.py` is listed in .gitignore and deleted after the build.

Debug logging
-------------
Pass `--debug-logging` to bake `gui/_build_flags.py` with `DEBUG_LOGGING = True`.
Without the flag the file is written with `False` and no `gui.log` is created.
`gui/_build_flags.py` is listed in .gitignore and deleted after the build.

SmartScreen / antivirus false positives
---------------------------------------
This build embeds Windows version metadata via `version_file.txt`, which
reduces (but does not eliminate) the "unknown publisher" SmartScreen prompt
on first launch.

To reduce false positives further, you can rebuild PyInstaller's bootloader
from source so it has a unique hash that AV vendors don't yet flag:

    # One-time setup (requires a C compiler; on Windows install
    # "Visual Studio Build Tools" with the C++ workload).
    git clone https://github.com/pyinstaller/pyinstaller.git
    cd pyinstaller/bootloader
    python ./waf all
    cd ..
    pip install --upgrade .

After that, run `python build_exe.py` as usual.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
APP_NAME = "MPCFillToPDF"
ENTRY = ROOT / "gui" / "main.py"
ASSETS = ROOT / "src" / "assets"
ICONS = ROOT / "icons"
RESOURCES = ROOT / "resources"
VERSION_FILE = ROOT / "version_file.txt"
BUNDLED_KEY_PATH = ROOT / "src" / "_bundled_key.py"
BUILD_FLAGS_PATH = ROOT / "gui" / "_build_flags.py"


def _embed_api_key() -> bool:
    """Read config.json, XOR-encode the API key, write src/_bundled_key.py.

    Returns True if a key was successfully embedded, False otherwise.
    The file must be deleted after the build regardless.
    """
    config_path = ROOT / "config.json"
    if not config_path.exists():
        print(
            "WARNING: config.json not found — API key will NOT be embedded.\n"
            "         Copy config.example.json to config.json and fill in your key."
        )
        return False

    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"WARNING: Could not parse config.json ({exc}) — API key not embedded.")
        return False

    key = str(data.get("google_drive_api_key", "")).strip()
    if not key or key.startswith("YOUR_"):
        print(
            "WARNING: google_drive_api_key is not set in config.json — "
            "API key will NOT be embedded."
        )
        return False

    key_bytes = key.encode("utf-8")
    mask = os.urandom(len(key_bytes))
    encoded = bytes(a ^ b for a, b in zip(key_bytes, mask))

    BUNDLED_KEY_PATH.write_text(
        "# Auto-generated by build_exe.py — do not commit.\n"
        f"_E = {encoded!r}\n"
        f"_M = {mask!r}\n"
        "\n"
        "def _get_key() -> str:\n"
        "    return bytes(a ^ b for a, b in zip(_E, _M)).decode('utf-8')\n",
        encoding="utf-8",
    )
    print(f"API key embedded (XOR-obfuscated) -> {BUNDLED_KEY_PATH.name}")
    return True


def _remove_bundled_key() -> None:
    try:
        BUNDLED_KEY_PATH.unlink()
        print(f"Cleaned up {BUNDLED_KEY_PATH.name}")
    except FileNotFoundError:
        pass


def _write_build_flags(debug_logging: bool) -> None:
    BUILD_FLAGS_PATH.write_text(
        f"# Auto-generated by build_exe.py — do not commit.\nDEBUG_LOGGING = {debug_logging}\n",
        encoding="utf-8",
    )
    print(f"Build flags written (DEBUG_LOGGING={debug_logging}) -> {BUILD_FLAGS_PATH.name}")


def _remove_build_flags() -> None:
    try:
        BUILD_FLAGS_PATH.unlink()
        print(f"Cleaned up {BUILD_FLAGS_PATH.name}")
    except FileNotFoundError:
        pass


def _check_paths() -> None:
    missing = [p for p in (ENTRY, VERSION_FILE, ASSETS, ICONS, RESOURCES) if not p.exists()]
    if missing:
        for p in missing:
            print(f"ERROR: ruta requerida no encontrada: {p}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build MPCFillToPDF.exe")
    parser.add_argument(
        "--debug-logging",
        action="store_true",
        help="Enable gui.log file logging in the built exe (default: off)",
    )
    cli_args = parser.parse_args()

    if shutil.which("pyinstaller") is None:
        print("pyinstaller not found. Install it with: pip install pyinstaller", file=sys.stderr)
        sys.exit(1)

    _check_paths()
    _embed_api_key()
    _write_build_flags(cli_args.debug_logging)

    sep = ";" if sys.platform == "win32" else ":"
    args = [
        "pyinstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        "--windowed",
        "--log-level=WARN",
        "--name",
        APP_NAME,
        f"--version-file={VERSION_FILE}",
        f"--add-data={ASSETS}{sep}src/assets",
        f"--add-data={ICONS}{sep}icons",
        f"--add-data={RESOURCES}{sep}resources",
        "--hidden-import=PIL.Image",
        "--hidden-import=reportlab.pdfgen",
        "--hidden-import=gdown",
        "--hidden-import=windnd",
        str(ENTRY),
    ]
    print("Running:", " ".join(args))
    try:
        subprocess.run(args, check=True, cwd=ROOT)
    finally:
        _remove_bundled_key()
        _remove_build_flags()

    print(f"\nBuilt: {ROOT / 'dist' / (APP_NAME + '.exe')}")


if __name__ == "__main__":
    main()
